stages:
  data_ingestion:
    cmd: python src/ecg-analyzer/pipelines/pipeline-01-data_ingestion.py

    deps:
      - configs/config.yaml
      - data/raw/mitbih_train.csv
      - data/raw/mitbih_test.csv
      - src/ecg-analyzer/components/data_ingestion.py
      - src/ecg-analyzer/config/config.py
      - src/ecg-analyzer/entity/entity.py
      - src/ecg-analyzer/pipelines/pipeline-01-data_ingestion.py

    outs:
      - artifacts/data_ingestion/raw
